### ISSUE TITLE
运行lsserver命令遇错，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [chrisyer/lightsocks-nodejs#1]
hello.

root@ar:~/node-v8.10.0-linux-x64# lsserver --password my_password --listen 7890
/usr/local/lib/node_modules/lightsocks-nodejs/lib/core/secure-socket.js:28
    async socketWrite(socket,buffer){
          ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lightsocks-nodejs/lib/server.js:5:22)
    at Module._compile (module.js:570:32)
root@ar:~/node-v8.10.0-linux-x64#

**Comment by chrisyer** [comment]
请使用node8或者9的版本

**Comment by chrisyer** [comment]
现在更新lightsocks-nodejs试一下，我把async移除了，只用Promise。

**Comment by luckypoem** [comment]
现在ok了，可成功翻墙。

**Comment by luckypoem** [comment]
不过，感觉拿来翻墙的速度有点慢，是因为没有加密的原因吗？可否加上加密的功能呢？

**Comment by chrisyer** [comment]
@luckypoem 这个只有混淆，如果上加密功能的话，可能会更耗CPU和内存。至于翻墙的速度，我这里Youtube 1080P 有1M每秒啊，下载也是。

![1](https://user-images.githubusercontent.com/14369492/37443758-02ef71be-2849-11e8-9b07-2a7a86224c46.png)
![2](https://user-images.githubusercontent.com/14369492/37443760-07a630ee-2849-11e8-974d-4e27cf172782.png)

**Comment by luckypoem** [comment]
@chrisyer 
嗯，可能是我网络的问题，现在看youtube流畅了
